[build]
  command = "npm run build && cp -r netlify dist/"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# Redirect all requests to our serverless function
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[functions]
  directory = "dist/netlify/functions"
  node_bundler = "esbuild"